name: 🐞 Bug Report
description: Report a problem or bug.
title: "Bug: "
labels: [bug]
body:
  - type: input
    id: version
    attributes:
      label: Affected Version
      description: Mention the affected version number
      placeholder: "x.y.z"

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: What steps lead to the issue?
      placeholder: |
        1. Open ...
        2. Run ...
        3. Observe the error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should have happened?
      placeholder: "It should ..."
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: "The result was ..."
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / Screenshots
      description: If possible, add logs or a screenshot showing the issue
      placeholder: "Traceback or Screenshot"
